name: CI Pipeline

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        cd app
        pip install -r requirements.txt

    - name: Run Basic Test
      run: |
        echo "Application Test Passed"

    - name: Build Docker Image
      run: |
        cd app
        docker build -t devops-app:v1 .
